---
title: "ReproducibleFiguresAnalysis"
output: html_document
date: "2024-11-26"
---

Loading libraries
```{r}
library(tidyverse)
library(palmerpenguins)
library(janitor)
library(here)
library(ragg)
library(svglite)
```


Loading functions
```{r}
#Cleaning function file
source(here("functions", "cleaning.R"))

#Function file to save figures as .png and .svg files
source(here("functions", "png_and_svg_functions.R"))

#Functions to produce exploratory figures 
source(here("functions", "exploratory_figure_functions.R"))

#Linear model figure function
source(here("functions", "linear_model_figure.R"))

#Diagnostic plot function
source(here("functions", "diagnostic_plot_function.R"))
```


QUESTION 01: Data Visualisation for Science Communication
Loading dataset
```{r}
#Done
#Loading raw dataset
penguins_raw

#Preserving raw datast
write_csv(penguins_raw, here("data", "penguins_raw.csv"))
```


Cleaning dataset
```{r}
#Done
#Cleaning function to clean the data 
penguins_clean <- penguins_raw %>%
  clean_column_names() %>%
  remove_columns(c("comments", "delta")) %>%
  shorten_species() %>%
  remove_empty_columns_rows()

penguins_clean

#Saving cleaned dataset
write_csv(penguins_clean, here("data", "penguins_clean.csv"))
```


Making scatterplot (Culmen Length vs Culmen Depth)
```{r}
#Done
#Subset columns and removing NA values
species_culmen_length_and_depth <- penguins_clean %>% select(species, culmen_length_mm, culmen_depth_mm) %>%
  drop_na()

species_culmen_length_and_depth
```


```{r}
#Done
#scatter plot for three species function 
scatterplot <- three_species_scatterplot(species_culmen_length_and_depth,
                          culmen_length_mm, culmen_depth_mm, species,
                          "Culmen Length (mm)", "Culmen Depth (mm)")

scatterplot

#Saving scatterplot as .png 
save_as_png(species_culmen_length_and_depth, 
            here("figures", "clvscd_scatterplot_report.png"), 
            scatterplot,
            size = 20, res = 300, scaling = 2)

#Saving scatterplot as .svg
save_as_svg(species_culmen_length_and_depth,
            here("figures", "clvscd_scatterplot_report.svg"),
            scatterplot,
            size = 20, scaling = 2)
```


QUESTION 02: Data Pipeline
Load the data
```{r}
#Done
#Loading raw dataset
penguins_raw

#Preserving raw datast
write_csv(penguins_raw, here("data", "penguins_raw.csv"))
```


Clean and subset the data
```{r}
#Done
#Clean and subset the data
clean_gentoo_body_mass_sex <- penguins_clean %>%
  filter(species == "Gentoo") %>%  #filter by Gentoo species 
  select(species, body_mass_g, sex) %>% #subset species, body mass and sex 
  remove_NA() 

#visualise the data 
head(clean_gentoo_body_mass_sex)

#save cleaned data set
write_csv(clean_gentoo_body_mass_sex, here("data", "clean_gentoo_body_mass.csv"))
```


Create an Exploratory Figure
```{r}
#Done
#Histogram function
histogram <- overlapping_histogram_comparing_sexes(clean_gentoo_body_mass_sex, body_mass_g, sex, "Body Mass(g)", "Count")

histogram


#Saving histogram as .png 
save_as_png(clean_gentoo_body_mass_sex, 
            here("figures", "histogram.png"), 
            histogram,
            size = 20, res = 300, scaling = 2)


#Saving histogram as .svg
save_as_svg(clean_gentoo_body_mass_sex,
            here("figures", "histogram.svg"),
            histogram,
            size = 20, scaling = 2)
```


Run a statistical test
```{r}
#Done
#Defining linear model
linear_model <- lm(body_mass_g ~ sex, data = clean_gentoo_body_mass_sex)
```


```{r}
#wrong
#Diagnostic plots 
#Displaying diagnostic plots in a multi-panel grid
par(mfrow = c(2, 2), 
    mar = c(4, 4, 2, 2)) #changing size of margins 


#Diagnostic plot function
diagnostic_plot_function()


# Saving the diagnostic plot as a .png
save_diagnostic_plot_as_png(
  here("figures", "diagnostic_plot.png"),  
  diagnostic_plot_function,                    
  size = 20,                               
  res = 300,                              
  scaling = 2                              
)

# Saving the diagnostic plot as a .svg
save_diagnostic_plot_as_svg(
  here("figures", "diagnostic_plot.svg"),  
  diagnostic_plot_function,                    
  size = 20,                               
  scaling = 2                              
)
```


```{r}
#Done
#Linear model analysis summary table
linear_model_summary <- broom::tidy(linear_model)  #converting model into a clean structure and extracting key details 

#Summary table - estimate, SE, and statistic rounded to three decimal points and p-values to 4 significant figues  
linear_model_summary_table <- linear_model_summary %>%
  select(term, estimate, std.error, statistic, p.value) %>%
  mutate(    #rounding estimate, SE and statistic to 3 decimal places 
    estimate = round(estimate, 3),
    std.error = round(std.error, 3),
    statistic = round(statistic, 3),
    p.value = format(p.value, scientific = TRUE, digits = 4)) 

print(linear_model_summary_table)
```


```{r}
#Done
#Results figure function
linear_model_results_figure <-linear_model_figure(clean_gentoo_body_mass_sex, sex, body_mass_g, "Sex", "Body Mass (g)")

linear_model_results_figure

#Saving results figure as .png 
save_as_png(clean_gentoo_body_mass_sex, 
            here("figures", "results_figure.png"), 
            linear_model_results_figure,
            size = 20, res = 300, scaling = 2)


#Saving results figure as .svg
save_as_svg(clean_gentoo_body_mass_sex,
            here("figures", "results_figure.svg"),
            linear_model_results_figure,
            size = 20, scaling = 2)
```




QUESTION 3: Open Science
